#### Numpy Documentation:
https://numpy.org/doc/stable/

In [1]:
import numpy as np

In [2]:
arr = np.array([0, 1, 2, 3])
arr_2 = np.arange(10)
print(arr, "\n", arr_2)

[0 1 2 3] 
 [0 1 2 3 4 5 6 7 8 9]


In [3]:
# List vs Numpy array:
num_list = range(10000)
%timeit [i**2 for i in num_list]

100 loops, best of 5: 2.46 ms per loop


In [4]:
arr_3 = np.arange(10000)
%timeit arr_3**2

The slowest run took 10.26 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 5: 6.83 µs per loop


In [5]:
# Numpy Array Attributes:
print(arr_3.ndim)
print(len(arr_3))
print(arr_3.shape)

1
10000
(10000,)


In [8]:
# 2D & 3D Arrays:
arr_2d = np.array([[0,1,2],[3,4,5]])
print("2D Array details : \n", arr_2d)
print(arr_2d.ndim)
print(len(arr_2d))
print(arr_2d.shape)

arr_3d = np.array([[[0,1], [2,3]],[[4,5], [6,7]], [[8,9], [0,0]]])
print("3D Array details : \n", arr_3d)
print(arr_3d.ndim)
print(len(arr_3d))
print(arr_3d.shape)

2D Array details : 
 [[0 1 2]
 [3 4 5]]
2
2
(2, 3)
3D Array details : 
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]

 [[8 9]
  [0 0]]]
3
3
(3, 2, 2)


In [11]:
arr = np.arange(1, 20, 3)
print(arr, "\n")
arr_2 = np.linspace(1, 20, 40)
print(arr_2)

[ 1  4  7 10 13 16 19] 

[ 1.          1.48717949  1.97435897  2.46153846  2.94871795  3.43589744
  3.92307692  4.41025641  4.8974359   5.38461538  5.87179487  6.35897436
  6.84615385  7.33333333  7.82051282  8.30769231  8.79487179  9.28205128
  9.76923077 10.25641026 10.74358974 11.23076923 11.71794872 12.20512821
 12.69230769 13.17948718 13.66666667 14.15384615 14.64102564 15.12820513
 15.61538462 16.1025641  16.58974359 17.07692308 17.56410256 18.05128205
 18.53846154 19.02564103 19.51282051 20.        ]


In [12]:
arr

array([ 1,  4,  7, 10, 13, 16, 19])

In [14]:
type(arr)

numpy.ndarray

In [15]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
np.eye(2,3)

array([[1., 0., 0.],
       [0., 1., 0.]])

In [19]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [20]:
arr = [0,1,2,3]
arr_2 = np.diag(arr)
arr_2

array([[0, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3]])

In [21]:
np.diag(arr_2)

array([0, 1, 2, 3])

In [22]:
# Random Numbers:

a = np.random.rand(5)
print(a)

# For Standard Normal distribution:
b = np.random.randn(5)
print(b)

[0.55944969 0.5493631  0.64064836 0.41858505 0.398237  ]
[-2.47403488 -0.05494671  0.09085587 -0.36782933  1.03258281]


In [23]:
a.dtype

dtype('float64')

In [25]:
arr_2.dtype

dtype('int64')

In [26]:
arr = np.arange(10, dtype="float64")
print(arr)
print(arr.dtype)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
float64


In [28]:
a = np.array([(1+2j),(3+4j)])
b = np.array([True, False, False, True])
c = np.array(["A", "B", "C", "D"])
print(a, "\n", b, "\n", c)
print(a.dtype, "\n", b.dtype, "\n", c.dtype)

[1.+2.j 3.+4.j] 
 [ True False False  True] 
 ['A' 'B' 'C' 'D']
complex128 
 bool 
 <U1


In [29]:
arr_2[2,2]

2

In [30]:
arr_2[2:5]

array([[0, 0, 2, 0],
       [0, 0, 0, 3]])

In [31]:
# Slicing an array creates a view on the original array, which is a way of accessing data. The original array is not copied in memory.
a = np.arange(10)
print(a)
b = a[::2]
print(b)
print(np.shares_memory(a, b))

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
True


In [32]:
b[0]=10
print(b)
print(a)

[10  2  4  6  8]
[10  1  2  3  4  5  6  7  8  9]


In [33]:
c = a[::2].copy()
print(c)
print(np.shares_memory(a,c))

[10  2  4  6  8]
False


In [38]:
# Mask creates copy and not view:

a = np.random.randint(0, 30, 20)
mask = (a%2==0)
b = a[mask]
print(a)
print(b)
a[mask] = -1
print(a)

[28 26 24 12 19 16 21 14 24 18 22  5 20 14  9 29 25 17 19 24]
[28 26 24 12 16 14 24 18 22 20 14 24]
[-1 -1 -1 -1 19 -1 21 -1 -1 -1 -1  5 -1 -1  9 29 25 17 19 -1]


In [40]:
a[[2,4,7,5,2]]

array([-1, 19, -1, -1, -1])

In [41]:
a[[5, 10]] = 333
a

array([ -1,  -1,  -1,  -1,  19, 333,  21,  -1,  -1,  -1, 333,   5,  -1,
        -1,   9,  29,  25,  17,  19,  -1])