In [1]:
import numpy as np

In [2]:
a = np.array([0,1,2])
a + 1

array([1, 2, 3])

In [4]:
b = np.diag([1,2,3,4])
print(b * b)
print(b.dot(b))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [6]:
a == (a+1)

array([False, False, False])

In [7]:
np.array_equal(a,(a+1))

False

In [8]:
np.sin(a)

array([0.        , 0.84147098, 0.90929743])

In [9]:
np.log(a)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718])

In [10]:
np.exp(a)

array([1.        , 2.71828183, 7.3890561 ])

In [11]:
# Reductions:

np.sum(a)

3

In [13]:
b = np.array([[1,1],[2,2]])
b.sum(axis=0)

array([3, 3])

In [14]:
b.sum(axis=1)

array([2, 4])

In [15]:
a.min()

0

In [16]:
a.argmin()

0

In [17]:
a.argmax()

2

In [18]:
print(np.all([True, False]))
print(np.any([True, False]))

False
True


In [19]:
# Axis=0 -> Col, Axis=1 -> Row
x = np.array([1,2,3,4])
y = np.array([[1,2,3],[4,5,6]])
print(x.mean())
print(np.median(x))
print(np.median(y, axis=-1))

2.5
2.5
[2. 5.]


In [20]:
data = np.loadtxt("/content/populations.txt")
data

array([[ 1900., 30000.,  4000., 48300.],
       [ 1901., 47200.,  6100., 48200.],
       [ 1902., 70200.,  9800., 41500.],
       [ 1903., 77400., 35200., 38200.],
       [ 1904., 36300., 59400., 40600.],
       [ 1905., 20600., 41700., 39800.],
       [ 1906., 18100., 19000., 38600.],
       [ 1907., 21400., 13000., 42300.],
       [ 1908., 22000.,  8300., 44500.],
       [ 1909., 25400.,  9100., 42100.],
       [ 1910., 27100.,  7400., 46000.],
       [ 1911., 40300.,  8000., 46800.],
       [ 1912., 57000., 12300., 43800.],
       [ 1913., 76600., 19500., 40900.],
       [ 1914., 52300., 45700., 39400.],
       [ 1915., 19500., 51100., 39000.],
       [ 1916., 11200., 29700., 36700.],
       [ 1917.,  7600., 15800., 41800.],
       [ 1918., 14600.,  9700., 43300.],
       [ 1919., 16200., 10100., 41300.],
       [ 1920., 24700.,  8600., 47300.]])

In [21]:
x1, x2, x3, x4 = data.T
x1

array([1900., 1901., 1902., 1903., 1904., 1905., 1906., 1907., 1908.,
       1909., 1910., 1911., 1912., 1913., 1914., 1915., 1916., 1917.,
       1918., 1919., 1920.])

In [22]:
data[:,1:]

array([[30000.,  4000., 48300.],
       [47200.,  6100., 48200.],
       [70200.,  9800., 41500.],
       [77400., 35200., 38200.],
       [36300., 59400., 40600.],
       [20600., 41700., 39800.],
       [18100., 19000., 38600.],
       [21400., 13000., 42300.],
       [22000.,  8300., 44500.],
       [25400.,  9100., 42100.],
       [27100.,  7400., 46000.],
       [40300.,  8000., 46800.],
       [57000., 12300., 43800.],
       [76600., 19500., 40900.],
       [52300., 45700., 39400.],
       [19500., 51100., 39000.],
       [11200., 29700., 36700.],
       [ 7600., 15800., 41800.],
       [14600.,  9700., 43300.],
       [16200., 10100., 41300.],
       [24700.,  8600., 47300.]])

In [23]:
data[:,1:].std(axis=0)

array([20897.90645809, 16254.59153691,  3322.50622558])

In [24]:
np.argmax(data, axis=1)

array([3, 3, 1, 1, 2, 2, 3, 3, 3, 3, 3, 3, 1, 1, 1, 2, 3, 3, 3, 3, 3])

In [25]:
np.argmax(data, axis=0)

array([20,  3,  4,  0])

In [26]:
# Broadcasting:

a = np.tile(np.arange(0, 40, 10), (4,1))
print(a)

print("\n#####\n")

a= a.T
print(a)

[[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]]

#####

[[ 0  0  0  0]
 [10 10 10 10]
 [20 20 20 20]
 [30 30 30 30]]


In [27]:
a = np.tile(np.arange(0, 40, 10), (4,2))
a

array([[ 0, 10, 20, 30,  0, 10, 20, 30],
       [ 0, 10, 20, 30,  0, 10, 20, 30],
       [ 0, 10, 20, 30,  0, 10, 20, 30],
       [ 0, 10, 20, 30,  0, 10, 20, 30]])

In [29]:
a = np.tile(np.arange(0, 40, 10), (3,1))
b = np.array([0,1,2,3])
a+b

array([[ 0, 11, 22, 33],
       [ 0, 11, 22, 33],
       [ 0, 11, 22, 33]])

In [30]:
a = np.arange(0, 40, 10)
a.shape

(4,)

In [32]:
# Converts 1D to 2D Array
a = a[:, np.newaxis]
a.shape

(4, 1)

In [33]:
a+b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33]])

In [34]:
# Flattening:

a = np.array([[1,2,3], [4,5,6]])
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [35]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [36]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
a.shape

(2, 3)

In [38]:
# Reshaping:
b = a.ravel()
b.shape

(6,)

In [39]:
b = b.reshape(2,3)
b

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
b[0, 0] = 100
a
# Memory location is same for both a & b for optimization

array([[100,   2,   3],
       [  4,   5,   6]])

In [42]:
a = np.arange(4)
a.resize((8,))
a

array([0, 1, 2, 3, 0, 0, 0, 0])

In [46]:
a = np.array([[33,11,22],[55,44,66]])
print(a.sort(axis=1))
print(np.sort(a, axis=1))

None
[[11 22 33]
 [44 55 66]]


In [47]:
np.argsort(a)

array([[0, 1, 2],
       [0, 1, 2]])